title: Godfred Fianu
description: Chemistry PhD â†’ JavaScript | React | Java | SQL
profile_image: /assets/Picture_Fianu.jpg

theme: jekyll-theme-minimal

header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md

